### ISSUE TITLE
autocomplete focus error

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-inputs#3]
When we use:

(focus)="getFocus($event)"

we get follow error:

Cannot read property 'subscribe' of undefined

TypeError: Cannot read property 'subscribe' of undefined at FocusDirective.ngOnInit (http://localhost:54962/dist/app.bundle.js:93593:25) at checkAndUpdateDirectiveInline (http://localhost:54962/dist/app.bundle.js:11066:19) at checkAndUpdateNodeInline (http://localhost:54962/dist/app.bundle.js:12567:17) at checkAndUpdateNode (http://localhost:54962/dist/app.bundle.js:12506:16) at debugCheckAndUpdateNode (http://localhost:54962/dist/app.bundle.js:13370:59) at debugCheckDirectivesFn (http://localhost:54962/dist/app.bundle.js:13311:13) at Object.View_NHAutocomplete_0._co [as updateDirectives] (ng:///NHBasisModule/NHAutocomplete.ngfactory.js:76:5) at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:54962/dist/app.bundle.js:13296:21) at checkAndUpdateView (http://localhost:54962/dist/app.bundle.js:12473:14) at callViewAction (http://localhost:54962/dist/app.bundle.js:12841:21)

**Comment by PrasanthPalani** [comment]
Hi j-nord

Thanks for using Syncfusion components.

We are validated your query and we are unable to reproduce the reported issue on our end.  For your convenience, we have prepared a simple sample and shared through GitHub.  Please refer the below sample,

Sample:  [ej2-ng-AutoComplete sample](https://github.com/PrasanthPalani/ej2-ng-dropdown-focus)

In this sample, we have updated the value property when we focus the element. 

Please let us know if you have any concern.

Thanks,
Prasanth P

**Comment by j-nord** [comment]
Hi Prasanth,

your autocomplete (Javascript 2) doesn't run in a modal mask.
See: ng-bootstrap -> Modal
Your Windows always after the modal mask. (Also Datepicker)

Regards

j.nord

**Comment by PrasanthPalani** [comment]
Hi j-nord, 

Thanks for using Syncfusion components. 
 
Query: your autocomplete (JavaScript 2) doesn't run in a modal mask. 

We have checked with your query. This is because the z-index value of the element may be higher compared to the z-index value of the ej2 autocomplete. Since we have provided standard z-index values for our components, this can be resolved at the application level using open event by fetching the maximum z-index value in the sample and resetting the z-index value of AutoComplete as shown below. 

`// bind the open event handler
    onOpen(args: any) {
      document.querySelector('#overlay').classList.add('modal-backdrop', 'fade', 'in');
      let elements: Element[] = <NodeListOf<Element> & Element[]>document.querySelectorAll('body > *');
      let value: string[] =[];
      for (let i = 0; i < elements.length; i++) {
          var element = document.defaultView.getComputedStyle(elements[i], null);
          if (element.getPropertyValue('position') !== 'static') {
              // fetching z-index values 
              value.push(element.getPropertyValue('z-index') || element.getPropertyValue('zIndex'));
          }
      }
      // fetching maximum z-index value
      let index: string = Math.max.apply(Math, value);
      // setting z-index of autocomplete
      args.popup.element.style.zIndex = index + 1; 
      }
      
    // bind the open event handler
    onClose(args: any) {
       document.querySelector('#overlay').classList.remove('modal-backdrop', 'fade', 'in');
    }
`
For your convenience, we have prepared a simple sample based on your scenario. Please get that sample in the below GitHub location.

Sample Location: [ej2-ng-autocomplete zIndex](https://github.com/PrasanthPalani/ej2-ng-autocomplete-zIndex)

You can do the same for Datapicker component also to resolve the reported issue in it.

Regards,
Prasanth P

**Comment by j-nord** [comment]
Hi, 

it doesn't work: TypeError: Cannot read property 'classList' of null 
because the id "overlay" not in the DOM. 

Also we want not use "document" in the code because it should run under Angular Universal in the future. 

How can we get a solution:  
- running under ng-bootstrap modal mask 
- call it und angular universal

 Regards

 j.nord

**Comment by Gopigovin** [comment]
Hi @j-nord , 

Sample provided previously is the custom element (overlay) to act as in index.html page. Which is not present in your application. So, it throws an error. However now we have modified the sample to achieve your requirement “**show the popup element over the backdrop (bootstrap) element**”. Here, we have explained z-index calculation related code blocks in app.component.ts file. Please refer the below code snippet.

```
[app.component.ts]

onOpen(args: any) {
     // To fetch the available child elements in body
    let elements: Element[] = <NodeListOf<Element> & Element[]>document.querySelectorAll('body > *');
    let value: string[] = [];
    for (let i = 0; i < elements.length; i++) {
      var element = document.defaultView.getComputedStyle(elements[i], null);
      if (element.getPropertyValue('position') !== 'static') {
        value.push(element.getPropertyValue('z-index') || element.getPropertyValue('zIndex'));// fetching z-index values 
      }
    }
    // fetching maximum z-index value
    let index: string = Math.max.apply(Math, value);
    // setting z-index to calendar popup element
    args.popup.element.style.zIndex = index + 1;
      } 

```
We have modified the GitHub sample which is shared already with requirement “**show the popup element over the backdrop (bootstrap) element**”. Please get the sample from below GitHub location.  
  
Sample location: [ej2-ng-autocomplete](https://github.com/PrasanthPalani/ej2-ng-autocomplete-zIndex)  
  
Please let us know if you have any concern, we will happy to assist you.

Regards,
Gopi G.
