### ISSUE TITLE
autocomplete value empty

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-inputs#4]
When we Change the dataSource the value is empty. Why?

We do not want to start querying the data source until after 2 characters. Not before. But when we renew the datasource the value is empty.

**Comment by PrasanthPalani** [comment]
Hi j-nord

Thanks for your interest in Essential JS 2. We will resolve the issue “when we Change the data source, the value is empty” and the fix will be available at the end of next week.

Regards,
Prasanth P

**Comment by bharathm03** [comment]
@PrasanthPalani what is the status of this issue?

**Comment by PrinceOliver** [comment]
Hi @j-nord ,

Thanks for your  patience.         
     
We have fixed the reported issue  and rolled out in  v16.1.42 release. Now, you can upgrade the  npm package to this version on your application.         
        
Please let us know, if you have any other concern, we will be happy to assist you.         
     
Regards,
Prince
