### ISSUE TITLE
it is not possilble to set focus

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-inputs#6]
Version 16.1.32

we set the focus with:
[focus]="focusSettingEventEmitter"

example:
forum entry from Kent Weigel
[https://stackoverflow.com/questions/35790021/angular2-focusing-a-textbox-on-component-load](url)

With a input field it works. With the maskedtextbox we can't set the focus. We also tested other possibilities. But nothing worked.

Regards
j.nord

**Comment by PiramanayagamSyncfusion** [comment]
@j-nord ,

You can able to focus the MaskedTextBox component after it is created by using created event. You can also get the MaskedTextBox element from its instance by using ViewChild. Please refer to the below code example.
`<ejs-maskedtextbox #mask mask="000-000-0000" (created)="oncreate($event)"></ejs-maskedtextbox>

export class DefaultMaskedTextboxController {
  @ViewChild('mask')
  public mask: MaskedTextBoxComponent;
  
  public oncreate(args:any): void {
    this.mask.element.focus();
  }
  public btnclick(args:any): void {
    this.mask.element.focus();
  }
}
`
For your reference, we have prepared a sample based on this in the link: https://plnkr.co/edit/BFloopOzFTl9eoCD8xqn?p=preview

Please let us know whether the provided sample is helpful in achieving your requirement. If not, revert with more information to proceed further.

Regards,
Piramanayagam R

**Comment by PiramanayagamSyncfusion** [comment]
@j-nord ,

By default, on focusing the MaskedTextBox the entire mask gets selected. You can customize the MaskedTextBox cursor position at starting position by using focus event. Please refer to below code example.

`[ts]

@Component({
    selector: 'custom-input',
    template: `<label class="mb-0" *ngIf="_label">{{_label}}<label class="mb-0" *ngIf="_required && _label">   *
        <ejs-maskedtextbox #maskEle id="mask" name="mask" [placeholder]="_placeholder" [style.min-width]="_width" [mask]="_maskFormat" [required]="_required" [(ngModel)]="value" (blur)="onBlur()" (focus)="onMaskFocus($event)"></ejs-maskedtextbox>`,
providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})

onMaskFocus(args: MaskFocusEventArgs) {
    var proxy = this;
    setTimeout(function () {
        if (proxy.maskObj.element) {
            proxy.maskObj.element.setSelectionRange(args.selectionStart, args.selectionStart);
        }
    }, 0);
}
`

For your reference, we have prepared a sample based on this and it can be downloaded from the location: [Sample](https://github.com/syncfusion/ej2-ng-inputs/files/1987190/Mask_Demo.zip)

Are you expecting this behavior in your application? If not revert with more information about your use case scenario. This would be more helpful for us to provide an exact solution. 

Regards,
Piramanayagam R
